const shops = [
  {
    id: 1,
    name: 'Lighters',
    prefecture: '東京都',
    city: '渋谷区',
    address: '神南1-15-7',
    description: '渋谷駅徒歩10分に位置する「Lighters」。全席喫煙可能。煙草を吸いながら本格的なイタリアン料理やこだわりの自家製ドリンクを楽しめるお店です。',
    url: 'https://www.lighters-shibuya.com/',
    eyeCatch: '/shops/shop.jpg',
  },
  {
    id: 2,
    name: 'Lighters',
    prefecture: '東京都',
    city: '渋谷区',
    address: '神南1-15-7',
    description: '渋谷駅徒歩10分に位置する「Lighters」。全席喫煙可能。煙草を吸いながら本格的なイタリアン料理やこだわりの自家製ドリンクを楽しめるお店です。',
    url: 'https://www.lighters-shibuya.com/',
    eyeCatch: '/shops/shop.jpg',
  },
  {
    id: 3,
    name: 'Lighters',
    prefecture: '東京都',
    city: '渋谷区',
    address: '神南1-15-7',
    description: '渋谷駅徒歩10分に位置する「Lighters」。全席喫煙可能。煙草を吸いながら本格的なイタリアン料理やこだわりの自家製ドリンクを楽しめるお店です。',
    url: 'https://www.lighters-shibuya.com/',
    eyeCatch: '/shops/shop.jpg',
  },
  {
    id: 4,
    name: 'Lighters',
    prefecture: '東京都',
    city: '渋谷区',
    address: '神南1-15-7',
    description: '渋谷駅徒歩10分に位置する「Lighters」。全席喫煙可能。煙草を吸いながら本格的なイタリアン料理やこだわりの自家製ドリンクを楽しめるお店です。',
    url: 'https://www.lighters-shibuya.com/',
    eyeCatch: '/shops/shop.jpg',
  },
  {
    id: 5,
    name: 'Lighters',
    prefecture: '東京都',
    city: '渋谷区',
    address: '神南1-15-7',
    description: '渋谷駅徒歩10分に位置する「Lighters」。全席喫煙可能。煙草を吸いながら本格的なイタリアン料理やこだわりの自家製ドリンクを楽しめるお店です。',
    url: 'https://www.lighters-shibuya.com/',
    eyeCatch: '/shops/shop.jpg',
  },
  {
    id: 6,
    name: 'Lighters',
    prefecture: '東京都',
    city: '渋谷区',
    address: '神南1-15-7',
    description: '渋谷駅徒歩10分に位置する「Lighters」。全席喫煙可能。煙草を吸いながら本格的なイタリアン料理やこだわりの自家製ドリンクを楽しめるお店です。',
    url: 'https://www.lighters-shibuya.com/',
    eyeCatch: '/shops/shop.jpg',
  },
  {
    id: 7,
    name: 'Lighters',
    prefecture: '東京都',
    city: '渋谷区',
    address: '神南1-15-7',
    description: '渋谷駅徒歩10分に位置する「Lighters」。全席喫煙可能。煙草を吸いながら本格的なイタリアン料理やこだわりの自家製ドリンクを楽しめるお店です。',
    url: 'https://www.lighters-shibuya.com/',
    eyeCatch: '/shops/shop.jpg',
  },
  {
    id: 8,
    name: 'Lighters',
    prefecture: '東京都',
    city: '渋谷区',
    address: '神南1-15-7',
    description: '渋谷駅徒歩10分に位置する「Lighters」。全席喫煙可能。煙草を吸いながら本格的なイタリアン料理やこだわりの自家製ドリンクを楽しめるお店です。',
    url: 'https://www.lighters-shibuya.com/',
    eyeCatch: '/shops/shop.jpg',
  },
  {
    id: 9,
    name: 'Lighters',
    prefecture: '東京都',
    city: '渋谷区',
    address: '神南1-15-7',
    description: '渋谷駅徒歩10分に位置する「Lighters」。全席喫煙可能。煙草を吸いながら本格的なイタリアン料理やこだわりの自家製ドリンクを楽しめるお店です。',
    url: 'https://www.lighters-shibuya.com/',
    eyeCatch: '/shops/shop.jpg',
  },
  {
    id: 10,
    name: 'Lighters',
    prefecture: '東京都',
    city: '渋谷区',
    address: '神南1-15-7',
    description: '渋谷駅徒歩10分に位置する「Lighters」。全席喫煙可能。煙草を吸いながら本格的なイタリアン料理やこだわりの自家製ドリンクを楽しめるお店です。',
    url: 'https://www.lighters-shibuya.com/',
    eyeCatch: '/shops/shop.jpg',
  },
]

export default shops;