import type { Metadata } from "next";
import { Suspense } from 'react';
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import '@mantine/core/styles.css';

const notoSansJP = Noto_Sans_JP({ subsets: [ 'latin'] });

export const metadata: Metadata = {
  title: "Smoke Map",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={notoSansJP.className}>
        <MantineProvider>
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
