import type { Metadata } from "next";
import { Suspense } from 'react';
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import '@mantine/core/styles.css';

import Header from "@/app/_components/organisms/projects/header";
import Footer from "@/app/_components/organisms/projects/footer";

const notoSansJP = Noto_Sans_JP({ subsets: [ 'latin'] });

export const metadata: Metadata = {
  title: "Smoke Map",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`flex flex-col min-h-screen ${notoSansJP.className}`}>
        <MantineProvider>
          <Suspense>
            <Header />
          </Suspense>
          <div className="border-b-2 border-slate-100"></div>
          <main className='flex-grow'>
            {children}
          </main>
          <Suspense>
            <Footer />
          </Suspense>
        </MantineProvider>
      </body>
    </html>
  );
}
